INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Apple Gift Card $25', 'Use the Apple Gift Card to get products, accessories, apps, games, music, movies, TV shows, and more. Spend it on in-app content, books, subscriptions and even iCloud storage to secure files from all your Apple devices. This gift card does it all. And then some.', '25', '365');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Apple Gift Card $50', 'Use the Apple Gift Card to get products, accessories, apps, games, music, movies, TV shows, and more. Spend it on in-app content, books, subscriptions and even iCloud storage to secure files from all your Apple devices. This gift card does it all. And then some.', '50', '365');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Apple Gift Card $100', 'Use the Apple Gift Card to get products, accessories, apps, games, music, movies, TV shows, and more. Spend it on in-app content, books, subscriptions and even iCloud storage to secure files from all your Apple devices. This gift card does it all. And then some.', '100', '365');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Domino’s® Pizza Gift Card $20', 'Domino''s® is more than pizza! Try our mouth-watering Bread Twists, Oven Baked Sandwiches, Pastas, Chicken, pizza & more. Order online at www.dominos.com for lunch, dinner or for your next event. No expiration date and no service fees. Can be redeemed at nearly 5,500 stores in the United States. For full details, visit www.dominos.com.', '20', '120');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Domino’s® Pizza Gift Card $30', 'Domino''s® is more than pizza! Try our mouth-watering Bread Twists, Oven Baked Sandwiches, Pastas, Chicken, pizza & more. Order online at www.dominos.com for lunch, dinner or for your next event. No expiration date and no service fees. Can be redeemed at nearly 5,500 stores in the United States. For full details, visit www.dominos.com.', '30', '120');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Domino’s® Pizza Gift Card $40', 'Domino''s® is more than pizza! Try our mouth-watering Bread Twists, Oven Baked Sandwiches, Pastas, Chicken, pizza & more. Order online at www.dominos.com for lunch, dinner or for your next event. No expiration date and no service fees. Can be redeemed at nearly 5,500 stores in the United States. For full details, visit www.dominos.com.', '40', '120');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Google Play Gift Code $25', 'Power up in over 1M Android apps and games on Google Play, the world''s largest mobile gaming platform. Use a Google Play gift code to go further in your favorite games like Clash Royale or Pokemon Go or redeem your code for the latest apps, movies, music, books, and more. There’s no credit card required, and balances never expire. Treat yourself or give the gift of Play today.', '25', '365');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Google Play Gift Code $50', 'Power up in over 1M Android apps and games on Google Play, the world''s largest mobile gaming platform. Use a Google Play gift code to go further in your favorite games like Clash Royale or Pokemon Go or redeem your code for the latest apps, movies, music, books, and more. There’s no credit card required, and balances never expire. Treat yourself or give the gift of Play today.', '50', '365');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Google Play Gift Code $100', 'Power up in over 1M Android apps and games on Google Play, the world''s largest mobile gaming platform. Use a Google Play gift code to go further in your favorite games like Clash Royale or Pokemon Go or redeem your code for the latest apps, movies, music, books, and more. There’s no credit card required, and balances never expire. Treat yourself or give the gift of Play today.', '100', '365');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Target GiftCard™ $25', 'A Target GiftCard™ is your opportunity to shop for thousands of items at more than 1,800 Target stores in the U.S. and online at Target.com. From toys and electronics to clothing and housewares, find exactly what you''re looking for at Target. No fees. No expiration. No kidding.', '25', '30');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Target GiftCard™ $50', 'A Target GiftCard™ is your opportunity to shop for thousands of items at more than 1,800 Target stores in the U.S. and online at Target.com. From toys and electronics to clothing and housewares, find exactly what you''re looking for at Target. No fees. No expiration. No kidding.', '50', '30');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('Target GiftCard™ $100', 'A Target GiftCard™ is your opportunity to shop for thousands of items at more than 1,800 Target stores in the U.S. and online at Target.com. From toys and electronics to clothing and housewares, find exactly what you''re looking for at Target. No fees. No expiration. No kidding.', '100', '30');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('The Home Depot® eGift Card $25', 'Whether remodeling your kitchen or purchasing new appliances and power tools, The Home Depot® provides products and services for all your home improvement needs.', '25', '60');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('The Home Depot® eGift Card $50', 'Whether remodeling your kitchen or purchasing new appliances and power tools, The Home Depot® provides products and services for all your home improvement needs.', '50', '60');
INSERT INTO gift_certificate (name, description, price, duration) VALUES ('The Home Depot® eGift Card $100', 'Whether remodeling your kitchen or purchasing new appliances and power tools, The Home Depot® provides products and services for all your home improvement needs.', '100', '60');


INSERT INTO tag (name) VALUES ('Apple');
INSERT INTO tag (name) VALUES ('Dominos');
INSERT INTO tag (name) VALUES ('Google Play');
INSERT INTO tag (name) VALUES ('Toys');
INSERT INTO tag (name) VALUES ('The Home Depot');
INSERT INTO tag (name) VALUES ('Electronics');
INSERT INTO tag (name) VALUES ('App');
INSERT INTO tag (name) VALUES ('Music');
INSERT INTO tag (name) VALUES ('Pizza');
INSERT INTO tag (name) VALUES ('Food');
INSERT INTO tag (name) VALUES ('Games');
INSERT INTO tag (name) VALUES ('Home');


insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Darby', 'Hilary', 'dhilary0@studiopress.com', 'BR2G4rN', '42 Bluestem Street', '2004-02-22');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Valentino', 'Chaman', 'vchaman1@bravesites.com', '0ABODzewQDUC', '08 Packers Alley', '2004-03-31');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Nanete', 'Hadwen', 'nhadwen2@issuu.com', 'nI8NIXv9GnF7', '9 Forest Dale Circle', '2001-12-15');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Lucias', 'Isaacs', 'lisaacs3@unc.edu', 'nxceGe', '7001 Maple Wood Avenue', '2001-04-08');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Carrol', 'Pinwill', 'cpinwill4@dyndns.org', 'emBqhDlf', '63311 Norway Maple Park', '2005-08-09');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Farlee', 'Budcock', 'fbudcock5@nhs.uk', 'vERp6XAnB', '71361 2nd Street', '1997-03-19');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Pincas', 'Senecaux', 'psenecaux6@skyrock.com', 'mRklWCX', '31519 Fallview Trail', '2006-07-15');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Beverie', 'Novacek', 'bnovacek7@tripadvisor.com', '48F1ZNK9ptw', '5 Riverside Park', '1996-01-23');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Lisha', 'Gyorgy', 'lgyorgy8@ft.com', 'CcBxI3iCY8P', '7367 Basil Avenue', '2010-02-04');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Erina', 'Grishmanov', 'egrishmanov9@nasa.gov', 'Bf9WwT3r7eKb', '10 Eliot Park', '1994-09-22');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Sophronia', 'Birney', 'sbirneya@blogs.com', 'fyIguUR1', '410 Northwestern Point', '2004-11-03');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Gwenette', 'Brazelton', 'gbrazeltonb@reference.com', 'k60Cgo5WCkI', '32 Harbort Court', '2003-11-23');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Clarette', 'Trahearn', 'ctrahearnc@google.com.hk', 'c685eLfYzyXl', '213 Loeprich Avenue', '1996-01-22');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Linea', 'Blaber', 'lblaberd@diigo.com', 'SkMYl79', '3276 Acker Place', '1998-08-07');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Stanfield', 'Nevinson', 'snevinsone@cbc.ca', 'CrKwq3Zp', '06612 Fremont Alley', '2004-05-20');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Elaina', 'Plain', 'eplainf@examiner.com', 'PanmOtQcz', '651 Elka Parkway', '1992-06-27');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Ulrike', 'Pierri', 'upierrig@parallels.com', '32r0bPzrtMdy', '0 Jana Street', '2006-05-26');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Hattie', 'Pilbeam', 'hpilbeamh@shinystat.com', 'Tuyl8LM', '40672 Morning Pass', '2010-03-17');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Meara', 'Rounds', 'mroundsi@macromedia.com', 'xWjCaJbWV', '59186 Goodland Drive', '2001-10-06');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Lanie', 'MacLennan', 'lmaclennanj@freewebs.com', 'sWKHpiG', '261 Clove Hill', '2002-11-09');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Rebbecca', 'Doring', 'rdoringk@ucoz.com', 'xjXVKUaH', '1172 Glendale Avenue', '1998-11-22');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Wendye', 'Skea', 'wskeal@mediafire.com', 'eIXpKpsiz3', '42 Village Green Junction', '2001-08-06');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Hort', 'D''Aeth', 'hdaethm@weather.com', 'Cc1R0nSGj1', '6926 Forest Junction', '2009-01-30');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Karissa', 'Cure', 'kcuren@reddit.com', 'qY4WSYJ', '9151 Eastlawn Place', '2008-11-11');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Audre', 'Gentsch', 'agentscho@wsj.com', 'hwRq0X', '0775 Forest Dale Trail', '2000-08-28');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Terrence', 'Forlong', 'tforlongp@yelp.com', 'CbB7hVv2Fdpx', '712 Dakota Parkway', '2002-02-05');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Imojean', 'Bosma', 'ibosmaq@java.com', 'C85hNPLz', '52977 Springs Hill', '2002-04-30');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Fitzgerald', 'Hainey', 'fhaineyr@imdb.com', 'FamjZcp', '710 Knutson Drive', '2002-05-10');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Kathi', 'Scoggins', 'kscogginss@elegantthemes.com', 'MJwRZZ5Z2wc', '2014 Bunting Drive', '1993-11-15');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Chrissie', 'Mosedill', 'cmosedillt@businesswire.com', 'CFcl1pt', '13 Sachtjen Pass', '2002-10-15');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Jacquetta', 'Rottgers', 'jrottgersu@marketwatch.com', 'GR6ztqDt', '5487 Hazelcrest Junction', '2007-03-02');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Tasia', 'Baxendale', 'tbaxendalev@dyndns.org', 'ZWu6hha', '4 Del Sol Park', '2007-05-17');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Faunie', 'Banfield', 'fbanfieldw@theatlantic.com', 'ECtqcDz0iqEO', '8 Delaware Crossing', '1994-08-19');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Dorris', 'Loxly', 'dloxlyx@uol.com.br', '0lHLX63J7BA', '77 Dorton Lane', '2007-08-08');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Freddy', 'Pack', 'fpacky@squidoo.com', '1qyDY8sI', '55 Gateway Park', '1993-07-05');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Max', 'Tideswell', 'mtideswellz@cloudflare.com', 'sdhYX9u8', '7 Coleman Junction', '1992-10-12');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Trixy', 'Mitroshinov', 'tmitroshinov10@de.vu', 'uBGWmo9DjVe', '3 Brickson Park Center', '2007-10-28');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Alphonso', 'Budik', 'abudik11@state.tx.us', 'cT5BzhkjM99B', '497 Chive Street', '1993-05-05');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Hewe', 'Gyorgy', 'hgyorgy12@google.es', 'z8KIggRnbGlp', '53646 Ruskin Alley', '1999-01-29');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Fidela', 'Kornousek', 'fkornousek13@myspace.com', 'rTYPOajXWVtS', '074 Dawn Court', '2007-07-23');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Roseline', 'Hess', 'rhess14@gov.uk', 'dfUxLw', '48 Rieder Way', '2005-08-18');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Easter', 'Chase', 'echase15@umich.edu', '8cbMAmw5Fu', '5 Vera Alley', '2010-03-24');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Melosa', 'Clemenson', 'mclemenson16@wunderground.com', 'ls2i3vLZ', '45 Veith Court', '2003-01-23');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Wainwright', 'Casillis', 'wcasillis17@unblog.fr', 'WjKxea', '67 Mandrake Trail', '2003-12-25');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Lorilyn', 'Sotheron', 'lsotheron18@vk.com', 'ZPVbkacaOW', '21 Ronald Regan Terrace', '2000-01-16');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Uta', 'Spittal', 'uspittal19@independent.co.uk', 'UWFKGm61yi', '95 Jenna Terrace', '1994-04-06');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Asa', 'Parkey', 'aparkey1a@si.edu', '6Qekhe', '8 Marcy Road', '2005-10-24');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Adrea', 'Billsberry', 'abillsberry1b@state.tx.us', 'GhEgLOH7', '69892 Sunnyside Crossing', '1991-03-19');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Hadleigh', 'Crooke', 'hcrooke1c@biblegateway.com', 'T2QKIskpmNOP', '59 Marcy Terrace', '2009-02-19');
insert into users (first_name, last_name, email, password, address, date_of_birth) values ('Jessie', 'Rounsefell', 'jrounsefell1d@mapy.cz', 'AH5vUfxjiD', '93423 Toban Pass', '2004-01-17');

INSERT INTO orders (certificate_id, cost, user_id) VALUES ('1', '25', '1');
INSERT INTO orders (certificate_id, cost, user_id) VALUES ('2', '50', '1');
INSERT INTO orders (certificate_id, cost, user_id) VALUES ('2', '50', '1');
INSERT INTO orders (certificate_id, cost, user_id) VALUES ('2', '100', '1');
INSERT INTO orders (certificate_id, cost, user_id) VALUES ('2', '50', '2');
INSERT INTO orders (certificate_id, cost, user_id) VALUES ('3', '100', '3');
